In [14]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("../data/ready_for_surrogates.csv", low_memory=False)
df.head().T

,0,1,2,3,4
value,0.36609,0.61967,0.642549,0.594286,0.7028
params_alpha,60.530821,0.507941,60.530821,0.507941,0.829182
params_booster,dart,gbtree,dart,gbtree,dart
params_colsample_bytree,0.83338,0.693547,0.83338,0.693547,0.573049
params_gamma,4.375872,5.684339,4.375872,5.684339,2.088768
params_grow_policy,lossguide,depthwise,lossguide,depthwise,depthwise
params_lambda,22.420124,0.00013,22.420124,0.00013,0.000929
params_learning_rate,0.003691,0.073092,0.003691,0.073092,0.452861
params_max_delta_step,10,3,10,3,1
params_max_depth,8,5,8,5,7
params_min_child_weight,8.66328,2.335883,8.66328,2.335883,0.202365
params_n_estimators,700,500,700,500,700
params_normalize_type,forest,NaN,forest,NaN,tree
params_params_scale_pos_weight,3.14868,2.492305,3.14868,2.492305,0.623833
params_rate_drop,0.035518,NaN,0.035518,NaN,0.328165
params_sample_type,weighted,NaN,weighted,NaN,weighted
params_skip_drop,0.078416,NaN,0.078416,NaN,0.124365
params_subsample,0.506753,0.689677,0.506753,0.689677,0.402633
user_attrs_acc_test,0.776538,0.725356,0.848603,0.684,0.862524
user_attrs_acc_val,0.778767,0.726044,0.847256,0.694717,0.864148
user_attrs_decision_threshold,0.691447,0.474813,0.691447,0.474813,0.635178
user_attrs_f1_test,0.353185,0.62067,0.652735,0.583906,0.702415
user_attrs_f1_val,0.36609,0.61967,0.642549,0.594286,0.7028
user_attrs_feature_fraction,0.571677,0.564463,0.571677,0.564463,0.869632
user_attrs_pr_auc_test,0.530758,0.776179,0.751059,0.672695,0.815087
user_attrs_pr_auc_val,0.528472,0.767155,0.74661,0.673019,0.810845
user_attrs_prec_test,0.574735,0.463569,0.723581,0.426294,0.728736
user_attrs_prec_val,0.58209,0.463928,0.729995,0.435667,0.737312
user_attrs_rec_test,0.254919,0.938837,0.594525,0.926433,0.67793
user_attrs_rec_val,0.267009,0.93282,0.573813,0.934531,0.671374
user_attrs_resampling_strategy,none,undersample,none,undersample,undersample
user_attrs_roc_auc_test,0.8029,0.905772,0.895726,0.871397,0.921522
user_attrs_roc_auc_val,0.799956,0.901404,0.892885,0.874227,0.920864
user_attrs_sample_rows,0.73074,0.530113,0.73074,0.530113,0.98823
params_params_labeled_ratio,1.0,1.0,1.0,1.0,1.0
params_params_missing_rate,0.0,0.0,0.0,0.0,0.0
params_params_selftrain_max_iter,0.0,0.0,0.0,0.0,0.0
params_params_selftrain_threshold,1.0,1.0,1.0,1.0,1.0
user_attrs_labeled_ratio,1.0,1.0,1.0,1.0,1.0
user_attrs_missing_rate,0.0,0.0,0.0,0.0,0.0
soft_risk_preference,recall_pref,recall_pref,recall_pref,recall_pref,balanced
soft_decision_speed,slow,balanced,slow,balanced,slow
soft_train_rows,21414,15535,21414,15535,28960

In [9]:
    columns_to_drop = [
                        "user_attrs_roc_auc_test", "user_attrs_roc_auc_val", 
                        "user_attrs_acc_val", "user_attrs_f1_test",
                        "user_attrs_f1_val", "user_attrs_pr_auc_test",
                        "user_attrs_pr_auc_val", "user_attrs_prec_test", 
                        "user_attrs_prec_val", "user_attrs_rec_test",
                        "user_attrs_rec_val", "user_attrs_acc_test"
    ]
    df_without_metrices = df.drop(columns_to_drop, axis=1)
    df_without_metrices.head().T

,0,1,2,3,4
value,0.36609,0.61967,0.642549,0.594286,0.7028
params_alpha,60.530821,0.507941,60.530821,0.507941,0.829182
params_booster,dart,gbtree,dart,gbtree,dart
params_colsample_bytree,0.83338,0.693547,0.83338,0.693547,0.573049
params_gamma,4.375872,5.684339,4.375872,5.684339,2.088768
params_grow_policy,lossguide,depthwise,lossguide,depthwise,depthwise
params_lambda,22.420124,0.00013,22.420124,0.00013,0.000929
params_learning_rate,0.003691,0.073092,0.003691,0.073092,0.452861
params_max_delta_step,10,3,10,3,1
params_max_depth,8,5,8,5,7
params_min_child_weight,8.66328,2.335883,8.66328,2.335883,0.202365
params_n_estimators,700,500,700,500,700
params_normalize_type,forest,NaN,forest,NaN,tree
params_params_scale_pos_weight,3.14868,2.492305,3.14868,2.492305,0.623833
params_rate_drop,0.035518,NaN,0.035518,NaN,0.328165
params_sample_type,weighted,NaN,weighted,NaN,weighted
params_skip_drop,0.078416,NaN,0.078416,NaN,0.124365
params_subsample,0.506753,0.689677,0.506753,0.689677,0.402633
user_attrs_decision_threshold,0.691447,0.474813,0.691447,0.474813,0.635178
user_attrs_feature_fraction,0.571677,0.564463,0.571677,0.564463,0.869632
user_attrs_resampling_strategy,none,undersample,none,undersample,undersample
user_attrs_sample_rows,0.73074,0.530113,0.73074,0.530113,0.98823
params_params_labeled_ratio,1.0,1.0,1.0,1.0,1.0
params_params_missing_rate,0.0,0.0,0.0,0.0,0.0
params_params_selftrain_max_iter,0.0,0.0,0.0,0.0,0.0
params_params_selftrain_threshold,1.0,1.0,1.0,1.0,1.0
user_attrs_labeled_ratio,1.0,1.0,1.0,1.0,1.0
user_attrs_missing_rate,0.0,0.0,0.0,0.0,0.0
soft_risk_preference,recall_pref,recall_pref,recall_pref,recall_pref,balanced
soft_decision_speed,slow,balanced,slow,balanced,slow
soft_train_rows,21414,15535,21414,15535,28960

In [22]:
bins = [0, 0.5, 0.6, 0.7, 1]
labels = ['very-low', 'low', 'moderate', 'high']
df_without_metrices["cat_value"] = pd.cut(df_without_metrices["value"], bins=bins, labels=labels, include_lowest=True)
df_without_metrices.head().T

,0,1,2,3,4
value,0.36609,0.61967,0.642549,0.594286,0.7028
params_alpha,60.530821,0.507941,60.530821,0.507941,0.829182
params_booster,dart,gbtree,dart,gbtree,dart
params_colsample_bytree,0.83338,0.693547,0.83338,0.693547,0.573049
params_gamma,4.375872,5.684339,4.375872,5.684339,2.088768
params_grow_policy,lossguide,depthwise,lossguide,depthwise,depthwise
params_lambda,22.420124,0.00013,22.420124,0.00013,0.000929
params_learning_rate,0.003691,0.073092,0.003691,0.073092,0.452861
params_max_delta_step,10,3,10,3,1
params_max_depth,8,5,8,5,7
params_min_child_weight,8.66328,2.335883,8.66328,2.335883,0.202365
params_n_estimators,700,500,700,500,700
params_normalize_type,forest,NaN,forest,NaN,tree
params_params_scale_pos_weight,3.14868,2.492305,3.14868,2.492305,0.623833
params_rate_drop,0.035518,NaN,0.035518,NaN,0.328165
params_sample_type,weighted,NaN,weighted,NaN,weighted
params_skip_drop,0.078416,NaN,0.078416,NaN,0.124365
params_subsample,0.506753,0.689677,0.506753,0.689677,0.402633
user_attrs_decision_threshold,0.691447,0.474813,0.691447,0.474813,0.635178
user_attrs_feature_fraction,0.571677,0.564463,0.571677,0.564463,0.869632
user_attrs_resampling_strategy,none,undersample,none,undersample,undersample
user_attrs_sample_rows,0.73074,0.530113,0.73074,0.530113,0.98823
params_params_labeled_ratio,1.0,1.0,1.0,1.0,1.0
params_params_missing_rate,0.0,0.0,0.0,0.0,0.0
params_params_selftrain_max_iter,0.0,0.0,0.0,0.0,0.0
params_params_selftrain_threshold,1.0,1.0,1.0,1.0,1.0
user_attrs_labeled_ratio,1.0,1.0,1.0,1.0,1.0
user_attrs_missing_rate,0.0,0.0,0.0,0.0,0.0
soft_risk_preference,recall_pref,recall_pref,recall_pref,recall_pref,balanced
soft_decision_speed,slow,balanced,slow,balanced,slow
soft_train_rows,21414,15535,21414,15535,28960
cat_value,very-low,moderate,moderate,low,high

In [25]:
acfx_df = df_without_metrices.drop("value", axis=1)
acfx_df.head().T

,0,1,2,3,4
params_alpha,60.530821,0.507941,60.530821,0.507941,0.829182
params_booster,dart,gbtree,dart,gbtree,dart
params_colsample_bytree,0.83338,0.693547,0.83338,0.693547,0.573049
params_gamma,4.375872,5.684339,4.375872,5.684339,2.088768
params_grow_policy,lossguide,depthwise,lossguide,depthwise,depthwise
params_lambda,22.420124,0.00013,22.420124,0.00013,0.000929
params_learning_rate,0.003691,0.073092,0.003691,0.073092,0.452861
params_max_delta_step,10,3,10,3,1
params_max_depth,8,5,8,5,7
params_min_child_weight,8.66328,2.335883,8.66328,2.335883,0.202365
params_n_estimators,700,500,700,500,700
params_normalize_type,forest,NaN,forest,NaN,tree
params_params_scale_pos_weight,3.14868,2.492305,3.14868,2.492305,0.623833
params_rate_drop,0.035518,NaN,0.035518,NaN,0.328165
params_sample_type,weighted,NaN,weighted,NaN,weighted
params_skip_drop,0.078416,NaN,0.078416,NaN,0.124365
params_subsample,0.506753,0.689677,0.506753,0.689677,0.402633
user_attrs_decision_threshold,0.691447,0.474813,0.691447,0.474813,0.635178
user_attrs_feature_fraction,0.571677,0.564463,0.571677,0.564463,0.869632
user_attrs_resampling_strategy,none,undersample,none,undersample,undersample
user_attrs_sample_rows,0.73074,0.530113,0.73074,0.530113,0.98823
params_params_labeled_ratio,1.0,1.0,1.0,1.0,1.0
params_params_missing_rate,0.0,0.0,0.0,0.0,0.0
params_params_selftrain_max_iter,0.0,0.0,0.0,0.0,0.0
params_params_selftrain_threshold,1.0,1.0,1.0,1.0,1.0
user_attrs_labeled_ratio,1.0,1.0,1.0,1.0,1.0
user_attrs_missing_rate,0.0,0.0,0.0,0.0,0.0
soft_risk_preference,recall_pref,recall_pref,recall_pref,recall_pref,balanced
soft_decision_speed,slow,balanced,slow,balanced,slow
soft_train_rows,21414,15535,21414,15535,28960
cat_value,very-low,moderate,moderate,low,high

In [26]:
csv_path = "../data/ready_for_acfx.csv"
acfx_df.to_csv(csv_path, index=False)
print(f"\nSaved clean dataset to: {csv_path}  | shape={acfx_df.shape}")

Saved clean dataset to: ../data/ready_for_acfx.csv  | shape=(11077, 31)